In [1]:
import  numpy as np

# methods of creating np objects

In [7]:
#creating from list
ar = np.array([1,2,3])
print(type(ar), ar)

<class 'numpy.ndarray'> [1 2 3]


In [8]:
#creating from ist of lists
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(type(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


# methods getting data about NP object:

In [9]:
#show number of rows and columns in array 
np.shape(ar)

(3, 3)