In [13]:
import  numpy as np
import pandas as pd

# methods of creating np objects

In [7]:
#creating from list
ar = np.array([1,2,3])
print(type(ar), ar)

<class 'numpy.ndarray'> [1 2 3]


In [12]:
#creating from ist of lists
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(type(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [19]:
#creating from Series with ".values"
ser = pd.Series([5, 6, 7, 8, 9, 10])
ser.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [32]:
np.empty(5) #creating empty array for 5 values
np.zeros((10, 7)) #creating array with 10 rows and 7 columns
np.ones((3,3,3)) #creating array with 3 directions, values = 1
np.eye(3) #array 3x3 with non-null values placed at diagonal
X = 33 
np.full((3, 5), X) #array with 3 rows and 5 columns filled by 'X'
np.arange(0, 21, 7)  # array filled with numbers in rage from 0 to 21 with step 7
np.linspace(0, 1, 5) #array with 5 elements in range from 0 to 1, cut range by equal parts
np.random.randint(0, 10, (3, 4)) #array 3x4 with random values in range from 0 to 10 (10 excluded!!!)

array([[8, 3, 4, 1],
       [5, 2, 8, 0],
       [6, 3, 6, 4]])

In [122]:
#creating np array based on list and generator
my_list = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_list, [x/2 for x in my_list], [x-100 for x in my_list]])
#and one more
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

# methods getting data about NP object:

In [9]:
#show number of rows and columns in array 
np.shape(ar)

(3, 3)

In [121]:
#number of elements in array
ar.size

9

## working with index

In [59]:
my_array = np.array([x for x in range(10)]) #to get value(s) need input index or slice
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [60]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]]) #for two dimentional arrays can be used doubled [] or index input with ','
my_array[1][2]
my_array[1,2]

12

## examples

In [63]:
#Unit 2 Chapter 9
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])


array([ 294.       ,   33.1662479, 2500.       ,   33.1662479,
        294.       ])

In [64]:
#to sum elements of last column
big_secret[:,-1].sum()

3154.332495807108

In [65]:
#to sum elements placed on digonal of array based on first 5 elements of 'big..'

Sum = 0
BS = np.array(big_secret[:5,:5]) #creating sub-array 5x5 by slicing o:5
for i in range(len(BS)):
    Sum += BS[i,i]
Sum

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [97]:
#to multiplay elements placed on digonal of array based on last 5 elements of 'big..'
mult = 1
BS = np.array(big_secret[:,-5:]) #creating sub-array 5x5 by slicing from -5 up to end
for i in range(len(BS)):
    mult *= BS[i,i]
mult


341505315559.2347

In [115]:
#change all elements with both even indexes to -1, and to 1 if both indexes are odd number
for i in range(len(big_secret[:,1])):
    for j in range(len(big_secret[1,:])):
        if i%2 and j%2:
            big_secret[i,j] = 1
        elif i%2 == 0 and j%2 == 0:
            big_secret[i,j] = -1
big_secret[:5,:5]

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [118]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

#same thing as above but using slicing method

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret[0::2,0::2]=-1
big_secret[1::2, 1::2]=1
big_secret[:5,:5]

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [119]:
#to multiplay elements placed on digonal of array based on last 5 elements of 'big..'
mult = 1
BS = np.array(big_secret[:,-5:]) #creating sub-array 5x5 by slicing from -5 up to end
for i in range(len(BS)):
    mult *= BS[i,i]
mult

-1.0

## Math methods with arrays

In [129]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b #multiplying elemnt per element
result4 = a/b
result5 = a*2
print('Sum: {}\nSubtraction: {}\nMultiply: {}\nDivision: {}\nMultiply with constant: {}'.format(result1, result2, result3, result4, result5))

Sum: [15 21 27]
Subtraction: [9 9 9]
Multiply: [ 36  90 162]
Division: [0.25 0.4  0.5 ]
Multiply with constant: [ 6 12 18]


In [130]:
#transpose
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [131]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[2, 9, 7, 8, 8],
       [8, 8, 8, 0, 1],
       [9, 1, 0, 9, 2],
       [4, 8, 1, 0, 3]])